import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";

const testimonials = [
  {
    name: "Asha R.",
    role: "Engineering Manager, FinTech",
    quote:
      "Onboarding time dropped from weeks to days. The autogenerated walkthroughs are gold.",
  },
  {
    name: "Miguel S.",
    role: "Staff Engineer, SaaS",
    quote:
      "We ship faster with less tribal knowledge. The Git-to-Gist KT packets changed our handovers.",
  },
  {
    name: "Priya K.",
    role: "Founder, AI Startup",
    quote: "Finally, RAG done right for codebases. Answers with citations is a killer feature.",
  },
];

export function TestimonialsSection() {
  return (
    <section id="testimonials" className="w-full border-t border-primary/20 py-20">
      <div className="mx-auto w-full max-w-7xl px-6">
        <div className="mb-10">
          <h2 className="text-2xl font-semibold tracking-tight sm:text-3xl md:text-4xl bg-[linear-gradient(90deg,_#9ca3af_0%,_#ffffff_20%,_#9ca3af_40%,_#9ca3af_100%)] bg-clip-text text-transparent [background-size:200%_100%] [animation:shine_3s_linear_infinite]">
            Teams love faster Knowledge Transfer
          </h2>
        </div>

        <div className="grid gap-6 md:grid-cols-3">
          {testimonials.map((t) => (
            <Card key={t.name} className="bg-secondary/40 backdrop-blur-sm">
              <CardHeader>
                <CardTitle className="text-base">“{t.quote}”</CardTitle>
              </CardHeader>
              <CardContent className="flex items-center gap-3">
                <Avatar>
                  <AvatarFallback>{t.name.split(/\s+/).filter(Boolean).map((p) => p[0]).join("").slice(0,2).toUpperCase() || "AI"}</AvatarFallback>
                </Avatar>
                <div>
                  <div className="text-sm font-medium">{t.name}</div>
                  <div className="text-xs text-muted-foreground">{t.role}</div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}

